Update CHANGELOG & README for Chat & Common for release
Azure/azure-sdk-for-android pull request #795
Opened 2021-06-08 21:49 UTC by CHILIU-MSFT

- Updated version number & date in CHANGELOG.md
- Updated version number in README.md

2021-06-08 22:16 UTC, vcolin7 commented on sdk/communication/azure-communication-chat/CHANGELOG.md
> +### Dependency Updates
nit; I think we can move this section to the end of this section, users are probably more interested to know about other changes.

2021-06-08 22:16 UTC, vcolin7 commented on sdk/communication/azure-communication-chat/CHANGELOG.md
> +- Updated Azure Core from 1.0.0-beta.5 to 1.0.0-beta.6
Just a small suggestion:

```suggestion
- Updated `com.azure.android.core` from `1.0.0-beta.5` to `1.0.0-beta.6`.
```

2021-06-08 22:16 UTC, vcolin7 commented on sdk/communication/azure-communication-common/CHANGELOG.md
> +- Updated Azure Core from 1.0.0-beta.5 to 1.0.0-beta.6
Just a small suggestion:

```suggestion
- Updated `com.azure.android.core` from `1.0.0-beta.5` to `1.0.0-beta.6`.
```

2021-06-08 22:16 UTC, vcolin7 commented on sdk/communication/azure-communication-chat/README.md
>  <dependency>
I think we need to change this **Include the package** section to look more like Common's **Install the library**, where they also include how to add the package to your project using gradle.

2021-06-08 22:32 UTC, vcolin7 approved these changes

2021-06-08 22:32 UTC, vcolin7 commented on sdk/communication/azure-communication-chat/README.md
> +# Azure Communication Chat client library for Android
Good catch!

2021-06-08 22:32 UTC, vcolin7 commented on sdk/communication/azure-communication-chat/README.md
> +
```suggestion

### Versions available
The current version of this library is **1.0.0**.

```

2021-06-08 22:46 UTC, JianpingChen commented
Don't you need to change Chat build.gradle for version 1.0.0? Currently it says version = "1.0.0-beta.9"

2021-06-08 22:49 UTC, vcolin7 requested changes
Let's add the version changes to build.gradle files

2021-06-09 00:22 UTC, JianpingChen approved these changes

2021-06-09 00:57 UTC, vcolin7 approved these changes

2021-06-09 00:57 UTC, vcolin7 commented on README.md
> +The following libraries are currently **general available**:
```suggestion
The following libraries are currently **generally available**:
```

2021-06-09 01:14 UTC, merged